### ISSUE TITLE
vendor/bin/console propel:database:create does not work on non-existing DBs

### ISSUE THREAD

**Issue by tonyfahrion** [spryker/support#206]
This is a

* [x] bug

For questions please consult the [Spryker Forum](http://discuss.spryker.com/).

Please provide the exact versions of the modules involved (see composer.lock file).

Demoshop version 2.31 and 2.32 (tested with both).

### What you did
Called `vendor/bin/console propel:database:create` to create a DB.

### Actual Behavior
The command failed with the following message:
```
root@9da2e24ca92b:/app# ./vendor/bin/console propel:database:create
Store: DE | Environment: development
Creating Database
[2018-06-08 06:20:08] Yves.CRITICAL: RuntimeException - createdb: could not connect to database template1: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
 in "/app/vendor/spryker/propel/src/Spryker/Zed/Propel/Business/Model/PropelDatabase/Adapter/PostgreSql/CreatePostgreSqlDatabase.php::117" {"exception":"[object] (RuntimeException(code: 0): createdb: could not connect to database template1: could not connect to server: No such file or directory
\tIs the server running locally and accepting
\tconnections on Unix domain socket \"/var/run/postgresql/.s.PGSQL.5432\"?
 at /app/vendor/spryker/propel/src/Spryker/Zed/Propel/Business/Model/PropelDatabase/Adapter/PostgreSql/CreatePostgreSqlDatabase.php:117)
[stacktrace]
#0 /app/vendor/spryker/propel/src/Spryker/Zed/Propel/Business/Model/PropelDatabase/Adapter/PostgreSql/CreatePostgreSqlDatabase.php(44): Spryker\\Zed\\Propel\\Business\\Model\\PropelDatabase\\Adapter\\PostgreSql\\CreatePostgreSqlDatabase->runProcess('PGPASSWORD=MxW8...')
#1 /app/vendor/spryker/propel/src/Spryker/Zed/Propel/Business/Model/PropelDatabase/Adapter/PostgreSql/CreatePostgreSqlDatabase.php(24): Spryker\\Zed\\Propel\\Business\\Model\\PropelDatabase\\Adapter\\PostgreSql\\CreatePostgreSqlDatabase->createDatabase()
#2 /app/vendor/spryker/propel/src/Spryker/Zed/Propel/Business/Model/PropelDatabase/Adapter/Adapter.php(76): Spryker\\Zed\\Propel\\Business\\Model\\PropelDatabase\\Adapter\\PostgreSql\\CreatePostgreSqlDatabase->createIfNotExists()
#3 /app/vendor/spryker/propel/src/Spryker/Zed/Propel/Business/PropelFacade.php(175): Spryker\\Zed\\Propel\\Business\\Model\\PropelDatabase\\Adapter\\Adapter->createIfNotExists()
#4 /app/vendor/spryker/propel/src/Spryker/Zed/Propel/Communication/Console/CreateDatabaseConsole.php(41): Spryker\\Zed\\Propel\\Business\\PropelFacade->createDatabase()
#5 /app/vendor/symfony/console/Command/Command.php(252): Spryker\\Zed\\Propel\\Communication\\Console\\CreateDatabaseConsole->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#6 /app/vendor/symfony/console/Application.php(964): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#7 /app/vendor/symfony/console/Application.php(248): Symfony\\Component\\Console\\Application->doRunCommand(Object(Spryker\\Zed\\Propel\\Communication\\Console\\CreateDatabaseConsole), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#8 /app/vendor/spryker/console/src/Spryker/Zed/Console/Communication/ConsoleBootstrap.php(150): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 /app/vendor/symfony/console/Application.php(148): Spryker\\Zed\\Console\\Communication\\ConsoleBootstrap->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#10 /app/vendor/spryker/console/bin/console(21): Symfony\\Component\\Console\\Application->run()
#11 {main}
"}
```

Running the command on an existing DB works well - it only happens, if the DB does not exists.
I guess that the command tries to use the specified DB while connecting to postgres; which fails.

### Expected Behavior
It should create the DB, if there is none.

Kind regards
Tony

**Comment by tonyfahrion** [comment]
Additional notes: the postgres version is 9.6.9 and running on a remote host. In addition, the user needs to authenticate via password

**Comment by tvaleriy** [comment]
Thank you for the feedback.
`$config[PropelConstants::USE_SUDO_TO_MANAGE_DATABASE] = false;` should be added to the appropriate configuration file in case of using remote host and this will solve the issue.
