### ISSUE TITLE
/vendor/bin/install fails when database exists

### ISSUE THREAD

**Issue by janmyszkier** [spryker/support#238]
This is a

* [x] bug
* [ ] enhancement

For questions please consult the [Spryker Forum](http://discuss.spryker.com/).

Please provide the exact versions of the modules involved (see composer.lock file).
```
{
            "name": "spryker/propel",
            "version": "3.6.1",
            "source": {
                "type": "git",
                "url": "https://github.com/spryker/propel.git",
                "reference": "29b4f609132c9bab4389de768bc054a2c80a5a95"
            },
```

### What you did
run `vendor/bin/install` within docker by:
`docker-compose exec spryker-php bash -c "cd /data/shop/development/current && vendor/bin/install"`

### Actual Behavior
Installer fails when trying to clean the DB:
```
                                                                                                     
 Section database-flush                                                                              
                                                                                                     

Command delete-elastic-search-index for DE store [vendor/bin/console search:index:delete] (In progresCommand delete-elastic-search-index for DE store [vendor/bin/console search:index:delete] (0.25s)
Command delete-elastic-search-index for AT store [vendor/bin/console search:index:delete] (In progresCommand delete-elastic-search-index for AT store [vendor/bin/console search:index:delete] (0.24s)
Command delete-elastic-search-index for US store [vendor/bin/console search:index:delete] (In progresCommand delete-elastic-search-index for US store [vendor/bin/console search:index:delete] (0.26s)
Command delete-storage for DE store [vendor/bin/console storage:delete] (0.29s)
Command delete-storage for AT store [vendor/bin/console storage:delete] (0.31s)
Command delete-storage for US store [vendor/bin/console storage:delete] (0.28s)
Command maintenance-zed-on [vendor/bin/console maintenance:enable zed] (0.24s)
Command drop-database for DE store [vendor/bin/console propel:database:drop] (In progress...)
Store: DE | Environment: development
Clear logs
Store: DE | Environment: development
Removed cache files
/data/shop/development/current/data/DE/cache
/data/shop/development/current/data/US/cache
Removed auto-load cache files
Store: DE | Environment: development
Store: DE | Environment: development
Jenkins disabled (response: 302)

Store: DE | Environment: development
Store: DE | Environment: development
Store: DE | Environment: development
Generated Yves IDE auto-completion files
Generated Zed IDE auto-completion files
Generated Client IDE auto-completion files
Generated Service IDE auto-completion files
Generated Glue IDE auto-completion files
Store: DE | Environment: development
Store: DE | Environment: development
Store: DE | Environment: development
Purge all queues
Store: AT | Environment: development
Purge all queues
Store: US | Environment: development
Purge all queues
Store: DE | Environment: development
Purge all queues
Store: AT | Environment: development
Purge all queues
Store: US | Environment: development
Purge all queues
Store: DE | Environment: development
Delete all queues
Store: AT | Environment: development
Delete all queues
Store: US | Environment: development
Delete all queues
Store: DE | Environment: development
Delete all exchanges
Store: AT | Environment: development
Delete all exchanges
Store: US | Environment: development
Delete all exchanges
Store: DE | Environment: development
Search index is empty
Store: AT | Environment: development
Search index is empty
Store: US | Environment: development
Search index is empty
Store: DE | Environment: development
Storage is empty
Store: AT | Environment: development
Storage is empty
Store: US | Environment: development
Storage is empty
Store: DE | Environment: development
Store: DE | Environment: development
Drop propel database
RuntimeException - Exception: psql: fe_sendauth: no password supplied
 
in /data/shop/development/current/vendor/spryker/propel/src/Spryker/Zed/Propel/Business/Model/PropelDatabase/Adapter/PostgreSql/DropPostgreSqlDatabase.php (148)

Command: vendor/bin/console propel:database:drop

Trace: 
#0 /data/shop/development/current/vendor/spryker/propel/src/Spryker/Zed/Propel/Business/Model/PropelDatabase/Adapter/PostgreSql/DropPostgreSqlDatabase.php(48): Spryker\Zed\Propel\Business\Model\PropelDatabase\Adapter\PostgreSql\DropPostgreSqlDatabase->runProcess('psql -h spryker...')
#1 /data/shop/development/current/vendor/spryker/propel/src/Spryker/Zed/Propel/Business/Model/PropelDatabase/Adapter/PostgreSql/DropPostgreSqlDatabase.php(30): Spryker\Zed\Propel\Business\Model\PropelDatabase\Adapter\PostgreSql\DropPostgreSqlDatabase->runDropCommandRemote()
#2 /data/shop/development/current/vendor/spryker/propel/src/Spryker/Zed/Propel/Business/Model/PropelDatabase/Adapter/Adapter.php(84): Spryker\Zed\Propel\Business\Model\PropelDatabase\Adapter\PostgreSql\DropPostgreSqlDatabase->dropDatabase()
#3 /data/shop/development/current/vendor/spryker/propel/src/Spryker/Zed/Propel/Business/PropelFacade.php(187): Spryker\Zed\Propel\Business\Model\PropelDatabase\Adapter\Adapter->dropDatabase()
#4 /data/shop/development/current/vendor/spryker/propel/src/Spryker/Zed/Propel/Communication/Console/DatabaseDropConsole.php(42): Spryker\Zed\Propel\Business\PropelFacade->dropDatabase()
#5 /data/shop/development/current/vendor/symfony/console/Command/Command.php(255): Spryker\Zed\Propel\Communication\Console\DatabaseDropConsole->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /data/shop/development/current/vendor/symfony/console/Application.php(964): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /data/shop/development/current/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Spryker\Zed\Propel\Communication\Console\DatabaseDropConsole), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /data/shop/development/current/vendor/spryker/console/src/Spryker/Zed/Console/Communication/ConsoleBootstrap.php(150): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /data/shop/development/current/vendor/symfony/console/Application.php(148): Spryker\Zed\Console\Communication\ConsoleBootstrap->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /data/shop/development/current/vendor/spryker/console/bin/console(21): Symfony\Component\Console\Application->run()
#11 {main}
In CommandLineExecutable.php line 101:
                      
  Aborted install...  
                      

install [-r|--recipe RECIPE] [-d|--dry-run] [-s|--sections SECTIONS] [-g|--groups GROUPS] [-x|--exclude EXCLUDE] [-e|--include-excluded INCLUDE-EXCLUDED] [-i|--interactive] [-b|--breakpoint] [-a|--ask-before-continue] [-l|--log] [--] [<store>]
```

### Expected Behavior
installer doesn't fail

### Possible fix:
changing `\Spryker\Zed\Propel\Business\Model\PropelDatabase\Adapter\PostgreSql\DropPostgreSqlDatabase::getDropCommandRemote` to
```
protected function getDropCommandRemote()
    {
        return sprintf(
            'PGPASSWORD=%s psql -h %s -p %s -U %s -w -c "DROP DATABASE IF EXISTS \"%s\"; " %s',
            Config::get(PropelConstants::ZED_DB_PASSWORD),
            Config::get(PropelConstants::ZED_DB_HOST),
            Config::get(PropelConstants::ZED_DB_PORT),
            $this->getConfigValue(PropelConstants::ZED_DB_USERNAME),
            $this->getConfigValue(PropelConstants::ZED_DB_DATABASE),
            'postgres'
        );
    }
```
fixed the issue for me

**Comment by vvs82** [comment]
Could you please try to set `PGPASSWORD` env variable before run the installation?

**Comment by tvaleriy** [comment]
Thank you for the report. I will notify when it is fixed and released.

**Comment by ohayamic** [comment]
how do one get to the directory

**Comment by tvaleriy** [comment]
Hi @janmyszkier, this should have been fixed in https://github.com/spryker/propel/releases/tag/3.9.0. Sorry for such a late notification.

Best,
Spryker Support Team
