### ISSUE TITLE
MySQL: Message Queue in B2C Demo Shop fails

### ISSUE THREAD

**Issue by KaiCMueller** [spryker/support#247]
This is a

* [x] bug
* [ ] enhancement

### What you did

after vagrant setup of b2c demo shop i performed:

1. core hack to fix https://github.com/spryker/support/issues/246 
vendor/spryker/event-behavior/src/Spryker/Zed/EventBehavior/Persistence/Propel/Schema/spy_event_behavior.schema.xml => added size="512" to "data" column
2. ulimit -n 65535
3. composer install
4. changed config_local to use MySQL as DB Engine
$config[PropelConstants::ZED_DB_PORT] = 3306;
$config[PropelConstants::ZED_DB_ENGINE] = $config[PropelConstants::ZED_DB_ENGINE_MYSQL];
$config[PropelQueryBuilderConstants::ZED_DB_ENGINE] = $config[PropelConstants::ZED_DB_ENGINE_MYSQL];
5. vendor/bin/install

After that, the shop was accessible, but no products were shown and data was missing:
![screenshot 2018-11-21 13 45 14](https://user-images.githubusercontent.com/1928209/48842144-c1ab3b00-ed93-11e8-80e6-466789016bf4.png)

Message Queue was full of errors:
![screenshot 2018-11-21 13 46 13](https://user-images.githubusercontent.com/1928209/48842186-e1dafa00-ed93-11e8-9a42-f784ba1b11bc.png)

Example error:
```
064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \u0027key, created_at, updated_at) VALUES (NULL, \u0027{\\\u0022items\\\u0022:[{\\\u0022name\\\u0022:\\\u0022Alternatives\u0027 at line 1\n\nExecuted query: \nINSERT INTO spy_product_label_dictionary_storage (id_product_label_dictionary_storage, data, locale, key, created_at, updated_at) VALUES (NULL, \u0027{\u0022items\u0022:[{\u0022name\u0022:\u0022Alternatives available\u0022,\u0022id_product_label\u0022:1,\u0022key\u0022:\u0022Alternatives available\u0022,\u0022is_exclusive\u0022:false,\u0022position\u0022:1,\u0022front_end_reference\u0022:null},{\u0022name\u0022:\u0022Discontinued\u0022,\u0022id_product_label\u0022:2,\u0022key\u0022:\u0022Discontinued\u0022,\u0022is_exclusive\u0022:false,\u0022position\u0022:2,\u0022front_end_reference\u0022:null},{\u0022name\u0022:\u0022Standard Label\u0022,\u0022id_product_label\u0022:3,\u0022key\u0022:\u0022Standard label\u0022,\u0022is_exclusive\u0022:false,\u0022position\u0022:3,\u0022front_end_reference\u0022:\u0022\u0022},{\u0022name\u0022:\u0022Neu\u0022,\u0022id_product_label\u0022:4,\u0022key\u0022:\u0022NEW\u0022,\u0022is_exclusive\u0022:false,\u0022position\u0022:4,\u0022front_end_reference\u0022:\u0022template:tag\u0022},{\u0022name\u0022:\u0022SALE %\u0022,\u0022id_product_label\u0022:5,\u0022key\u0022:\u0022SALE\u0022,\u0022is_exclusive\u0022:false,\u0022position\u0022:5,\u0022front_end_reference\u0022:\u0022highlight\u0022}]}\u0027, \u0027de_DE\u0027, \u0027product_label_dictionary:de_de\u0027, \u00272018-11-21 12:20:22.151571\u0027, \u00272018-11-21 12:20:22.151571\u0027)\u0022, \u0022#0 \/data\/shop\/development\/current\/src\/Orm\/Zed\/ProductLabelStorage\/Persistence\/Base\/SpyProductLabelDictionaryStorage.php(825): Orm\\Zed\\ProductLabelStorage\\Persistence\\Base\\SpyProductLabelDictionaryStorage-\u003EdoInsert(Object(Propel\\Runtime\\Connection\\ConnectionWrapper))\n#1 \/data\/shop\/development\/current\/src\/Orm\/Zed\/ProductLabelStorage\/Persistence\/Base\/SpyProductLabelDictionaryStorage.php(783): Orm\\Zed\\ProductLabelStorage\\Persistence\\Base\\SpyProductLabelDictionaryStorage-\u003EdoSave(Object(Propel\\Runtime\\Connection\\ConnectionWrapper))\n#2 [internal function]: Orm\\Zed\\ProductLabelStorage\\Persistence\\Base\\SpyProductLabelDictionaryStorage-\u003EOrm\\Zed\\ProductLabelStorage\\Persistence\\Base\\{closure}()\n#3 \/data\/shop\/development\/current\/vendor\/propel\/propel\/src\/Propel\/Runtime\/Connection\/TransactionTrait.php(35): call_user_func(Object(Closure))\n#4 \/data\/shop\/development\/current\/src\/Orm\/Zed\/ProductLabelStorage\/Persistence\/Base\/SpyProductLabelDictionaryStorage.php(802): Propel\\Runtime\\Connection\\ConnectionWrapper-\u003Etransaction(Object(Closure))\n#5 \/data\/shop\/development\/current\/vendor\/spryker\/product-label-storage\/src\/Spryker\/Zed\/ProductLabelStorage\/Business\/Storage\/ProductLabelDictionaryStorageWriter.php(125): Orm\\Zed\\ProductLabelStorage\\Persistence\\Base\\SpyProductLabelDictionaryStorage-\u003Esave()\n#6 \/data\/shop\/development\/current\/vendor\/spryker\/product-label-storage\/src\/Spryker\/Zed\/ProductLabelStorage\/Business\/Storage\/ProductLabelDictionaryStorageWriter.php(102): Spryker\\Zed\\ProductLabelStorage\\Business\\Storage\\ProductLabelDictionaryStorageWriter-\u003EstoreDataSet(Object(Generated\\Shared\\Transfer\\ProductLabelDictionaryStorageTransfer), \u0027de_DE\u0027)\n#7 \/data\/shop\/development\/current\/vendor\/spryker\/product-label-storage\/src\/Spryker\/Zed\/ProductLabelStorage\/Business\/Storage\/ProductLabelDictionaryStorageWriter.php(61): Spryker\\Zed\\ProductLabelStorage\\Business\\Storage\\ProductLabelDictionaryStorageWriter-\u003EstoreData(Array)\n#8 \/data\/shop\/development\/current\/vendor\/spryker\/product-label-storage\/src\/Spryker\/Zed\/ProductLabelStorage\/Business\/ProductLabelStorageFacade.php(26): Spryker\\Zed\\ProductLabelStorage\\Business\\Storage\\ProductLabelDictionaryStorageWriter-\u003Epublish()\n#9 \/data\/shop\/development\/current\/vendor\/spryker\/product-label-storage\/src\/Spryker\/Zed\/ProductLabelStorage\/Communication\/Plugin\/Event\/Listener\/ProductLabelDictionaryStorageListener.php(46): Spryker\\Zed\\ProductLabelStorage\\Business\\ProductLabelStorageFacade-\u003EpublishLabelDictionary()\n#10 \/data\/shop\/development\/current\/vendor\/spryker\/event\/src\/Spryker\/Zed\/Event\/Business\/Queue\/Consumer\/EventQueueConsumer.php(131): Spryker\\Zed\\ProductLabelStorage\\Communication\\Plugin\\Event\\Listener\\ProductLabelDictionaryStorageListener-\u003EhandleBulk(Array, \u0027Entity.spy_prod...\u0027)\n#11 \/data\/shop\/development\/current\/vendor\/spryker\/event\/src\/Spryker\/Zed\/Event\/Business\/Queue\/Consumer\/EventQueueConsumer.php(110): Spryker\\Zed\\Event\\Business\\Queue\\Consumer\\EventQueueConsumer-\u003EhandleBulk(Array, \u0027Spryker\\\\Zed\\\\Pro...\u0027)\n#12 \/data\/shop\/development\/current\/vendor\/spryker\/event\/src\/Spryker\/Zed\/Event\/Business\/EventFacade.php(65): Spryker\\Zed\\Event\\Business\\Queue\\Consumer\\EventQueueConsumer-\u003EprocessMessages(Array)\n#13 \/data\/shop\/development\/current\/vendor\/spryker\/event\/src\/Spryker\/Zed\/Event\/Communication\/Plugin\/Queue\/EventQueueMessageProcessorPlugin.php(29): Spryker\\Zed\\Event\\Business\\EventFacade-\u003EprocessEnqueuedMessages(Array)\n#14 \/data\/shop\/development\/current\/vendor\/spryker\/queue\/src\/Spryker\/Zed\/Queue\/Business\/Task\/TaskManager.php(59): Spryker\\Zed\\Event\\Communication\\Plugin\\Queue\\EventQueueMessageProcessorPlugin-\u003EprocessMessages(Array)\n#15 \/data\/shop\/development\/current\/vendor\/spryker\/queue\/src\/Spryker\/Zed\/Queue\/Business\/QueueFacade.php(32): Spryker\\Zed\\Queue\\Business\\Task\\TaskManager-\u003Erun(\u0027event\u0027, Array)\n#16 \/data\/shop\/development\/current\/vendor\/spryker\/queue\/src\/Spryker\/Zed\/Queue\/Communication\/Console\/QueueTaskConsole.php(53): Spryker\\Zed\\Queue\\Business\\QueueFacade-\u003EstartTask(\u0027event\u0027, Array)\n#17 \/data\/shop\/development\/current\/vendor\/symfony\/console\/Command\/Command.php(255): Spryker\\Zed\\Queue\\Communication\\Console\\QueueTaskConsole-\u003Eexecute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#18 \/data\/shop\/development\/current\/vendor\/symfony\/console\/Application.php(964): Symfony\\Component\\Console\\Command\\Command-\u003Erun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#19 \/data\/shop\/development\/current\/vendor\/symfony\/console\/Application.php(248): Symfony\\Component\\Console\\Application-\u003EdoRunCommand(Object(Spryker\\Zed\\Queue\\Communication\\Console\\QueueTaskConsole), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#20 \/data\/shop\/development\/current\/vendor\/spryker\/console\/src\/Spryker\/Zed\/Console\/Communication\/ConsoleBootstrap.php(150): Symfony\\Component\\Console\\Application-\u003EdoRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#21 \/data\/shop\/development\/current\/vendor\/symfony\/console\/Application.php(148): Spryker\\Zed\\Console\\Communication\\ConsoleBootstrap-\u003EdoRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#22 \/data\/shop\/development\/current\/vendor\/spryker\/console\/bin\/console(21): Symfony\\Component\\Console\\Application-\u003Erun()\n#23 {main}\u0022.","errorMessage":"Failed to handle \u0022Entity.spy_product_label.create\u0022 for listener \u0022Spryker\\Zed\\ProductLabelStorage\\Communication\\Plugin\\Event\\Listener\\ProductLabelDictionaryStorageListener\u0022. Exception: \u0022SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \u0027key, created_at, updated_at) VALUES (NULL, \u0027{\\\u0022items\\\u0022:[{\\\u0022name\\\u0022:\\\u0022Alternatives\u0027 at line 1\n\nExecuted query: \nINSERT INTO spy_product_label_dictionary_storage (id_product_label_dictionary_storage, data, locale, key, created_at, updated_at) VALUES (NULL, \u0027{\u0022items\u0022:[{\u0022name\u0022:\u0022Alternatives available\u0022,\u0022id_product_label\u0022:1,\u0022key\u0022:\u0022Alternatives available\u0022,\u0022is_exclusive\u0022:false,\u0022position\u0022:1,\u0022front_end_reference\u0022:null},{\u0022name\u0022:\u0022Discontinued\u0022,\u0022id_product_label\u0022:2,\u0022key\u0022:\u0022Discontinued\u0022,\u0022is_exclusive\u0022:false,\u0022position\u0022:2,\u0022front_end_reference\u0022:null},{\u0022name\u0022:\u0022Standard Label\u0022,\u0022id_product_label\u0022:3,\u0022key\u0022:\u0022Standard label\u0022,\u0022is_exclusive\u0022:false,\u0022position\u0022:3,\u0022front_end_reference\u0022:\u0022\u0022},{\u0022name\u0022:\u0022Neu\u0022,\u0022id_product_label\u0022:4,\u0022key\u0022:\u0022NEW\u0022,\u0022is_exclusive\u0022:false,\u0022position\u0022:4,\u0022front_end_reference\u0022:\u0022template:tag\u0022},{\u0022name\u0022:\u0022SALE %\u0022,\u0022id_product_label\u0022:5,\u0022key\u0022:\u0022SALE\u0022,\u0022is_exclusive\u0022:false,\u0022position\u0022:5,\u0022front_end_reference\u0022:\u0022highlight\u0022}]}\u0027, \u0027de_DE\u0027, \u0027product_label_dictionary:de_de\u0027, \u00272018-11-21 12:21:37.088644\u0027, \u00272018-11-21 12:21:37.088644\u0027)\u0022, \u0022#0 \/data\/shop\/development\/current\/src\/Orm\/Zed\/ProductLabelStorage\/Persistence\/Base\/SpyProductLabelDictionaryStorage.php(825): Orm\\Zed\\ProductLabelStorage\\Persistence\\Base\\SpyProductLabelDictionaryStorage-\u003EdoInsert(Object(Propel\\Runtime\\Connection\\ConnectionWrapper))\n#1 \/data\/shop\/development\/current\/src\/Orm\/Zed\/ProductLabelStorage\/Persistence\/Base\/SpyProductLabelDictionaryStorage.php(783): Orm\\Zed\\ProductLabelStorage\\Persistence\\Base\\SpyProductLabelDictionaryStorage-\u003EdoSave(Object(Propel\\Runtime\\Connection\\ConnectionWrapper))\n#2 [internal function]: Orm\\Zed\\ProductLabelStorage\\Persistence\\Base\\SpyProductLabelDictionaryStorage-\u003EOrm\\Zed\\ProductLabelStorage\\Persistence\\Base\\{closure}()\n#3 \/data\/shop\/development\/current\/vendor\/propel\/propel\/src\/Propel\/Runtime\/Connection\/TransactionTrait.php(35): call_user_func(Object(Closure))\n#4 \/data\/shop\/development\/current\/src\/Orm\/Zed\/ProductLabelStorage\/Persistence\/Base\/SpyProductLabelDictionaryStorage.php(802): Propel\\Runtime\\Connection\\ConnectionWrapper-\u003Etransaction(Object(Closure))\n#5 \/data\/shop\/development\/current\/vendor\/spryker\/product-label-storage\/src\/Spryker\/Zed\/ProductLabelStorage\/Business\/Storage\/ProductLabelDictionaryStorageWriter.php(125): Orm\\Zed\\ProductLabelStorage\\Persistence\\Base\\SpyProductLabelDictionaryStorage-\u003Esave()\n#6 \/data\/shop\/development\/current\/vendor\/spryker\/product-label-storage\/src\/Spryker\/Zed\/ProductLabelStorage\/Business\/Storage\/ProductLabelDictionaryStorageWriter.php(102): Spryker\\Zed\\ProductLabelStorage\\Business\\Storage\\ProductLabelDictionaryStorageWriter-\u003EstoreDataSet(Object(Generated\\Shared\\Transfer\\ProductLabelDictionaryStorageTransfer), \u0027de_DE\u0027)\n#7 \/data\/shop\/development\/current\/vendor\/spryker\/product-label-storage\/src\/Spryker\/Zed\/ProductLabelStorage\/Business\/Storage\/ProductLabelDictionaryStorageWriter.php(61): Spryker\\Zed\\ProductLabelStorage\\Business\\Storage\\ProductLabelDictionaryStorageWriter-\u003EstoreData(Array)\n#8 \/data\/shop\/development\/current\/vendor\/spryker\/product-label-storage\/src\/Spryker\/Zed\/ProductLabelStorage\/Business\/ProductLabelStorageFacade.php(26): Spryker\\Zed\\ProductLabelStorage\\Business\\Storage\\ProductLabelDictionaryStorageWriter-\u003Epublish()\n#9 \/data\/shop\/development\/current\/vendor\/spryker\/product-label-storage\/src\/Spryker\/Zed\/ProductLabelStorage\/Communication\/Plugin\/Event\/Listener\/ProductLabelDictionaryStorageListener.php(46): Spryker\\Zed\\ProductLabelStorage\\Business\\ProductLabelStorageFacade-\u003EpublishLabelDictionary()\n#10 \/data\/shop\/development\/current\/vendor\/spryker\/event\/src\/Spryker\/Zed\/Event\/Business\/Queue\/Consumer\/EventQueueConsumer.php(131): Spryker\\Zed\\ProductLabelStorage\\Communication\\Plugin\\Event\\Listener\\ProductLabelDictionaryStorageListener-\u003EhandleBulk(Array, \u0027Entity.spy_prod...\u0027)\n#11 \/data\/shop\/development\/current\/vendor\/spryker\/event\/src\/Spryker\/Zed\/Event\/Business\/Queue\/Consumer\/EventQueueConsumer.php(110): Spryker\\Zed\\Event\\Business\\Queue\\Consumer\\EventQueueConsumer-\u003EhandleBulk(Array, \u0027Spryker\\\\Zed\\\\Pro...\u0027)\n#12 \/data\/shop\/development\/current\/vendor\/spryker\/event\/src\/Spryker\/Zed\/Event\/Business\/EventFacade.php(65): Spryker\\Zed\\Event\\Business\\Queue\\Consumer\\EventQueueConsumer-\u003EprocessMessages(Array)\n#13 \/data\/shop\/development\/current\/vendor\/spryker\/event\/src\/Spryker\/Zed\/Event\/Communication\/Plugin\/Queue\/EventQueueMessageProcessorPlugin.php(29): Spryker\\Zed\\Event\\Business\\EventFacade-\u003EprocessEnqueuedMessages(Array)\n#14 \/data\/shop\/development\/current\/vendor\/spryker\/queue\/src\/Spryker\/Zed\/Queue\/Business\/Task\/TaskManager.php(59): Spryker\\Zed\\Event\\Communication\\Plugin\\Queue\\EventQueueMessageProcessorPlugin-\u003EprocessMessages(Array)\n#15 \/data\/shop\/development\/current\/vendor\/spryker\/queue\/src\/Spryker\/Zed\/Queue\/Business\/QueueFacade.php(32): Spryker\\Zed\\Queue\\Business\\Task\\TaskManager-\u003Erun(\u0027event\u0027, Array)\n#16 \/data\/shop\/development\/current\/vendor\/spryker\/queue\/src\/Spryker\/Zed\/Queue\/Communication\/Console\/QueueTaskConsole.php(53): Spryker\\Zed\\Queue\\Business\\QueueFacade-\u003EstartTask(\u0027event\u0027, Array)\n#17 \/data\/shop\/development\/current\/vendor\/symfony\/console\/Command\/Command.php(255): Spryker\\Zed\\Queue\\Communication\\Console\\QueueTaskConsole-\u003Eexecute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#18 \/data\/shop\/development\/current\/vendor\/symfony\/console\/Application.php(964): Symfony\\Component\\Console\\Command\\Command-\u003Erun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#19 \/data\/shop\/development\/current\/vendor\/symfony\/console\/Application.php(248): Symfony\\Component\\Console\\Application-\u003EdoRunCommand(Object(Spryker\\Zed\\Queue\\Communication\\Console\\QueueTaskConsole), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#20 \/data\/shop\/development\/current\/vendor\/spryker\/console\/src\/Spryker\/Zed\/Console\/Communication\/ConsoleBootstrap.php(150): Symfony\\Component\\Console\\Application-\u003EdoRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#21 \/data\/shop\/development\/current\/vendor\/symfony\/console\/Application.php(148): Spryker\\Zed\\Console\\Communication\\ConsoleBootstrap-\u003EdoRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#22 \/data\/shop\/development\/current\/vendor\/spryker\/console\/bin\/console(21): Symfony\\Component\\Console\\Application-\u003Erun()\n#23 {main}\u0022."}
```

### Actual Behavior
Data was not exported to the storage

### Expected Behavior
Data should be exported to storage without errors

**Comment by tvaleriy** [comment]
Fixed in master branch of spryker-shop/suite repository.
