### ISSUE TITLE
No Category Search in ZED

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#40]
When using the search field for root categories in PIM, I become an AJAX error
```
ZED Exception

Propel\Runtime\Exception\PropelException - Unable to execute COUNT statement [SELECT COUNT(*) FROM `spy_category_attribute` INNER JOIN spy_locale ON (`spy_category_attribute`.`fk_locale`=`spy_locale`.`id_locale`) INNER JOIN spy_category_node ON (`spy_category_attribute`.`fk_category`=`spy_category_node`.`fk_category`) WHERE `spy_category_node`.`is_root`=:p1 AND `spy_category_attribute`.`fk_locale`=:p2 AND (((LOWER(`spy_category_attribute`.`fk_category`) LIKE '%gale%' OR LOWER(`spy_category_attribute`.`name`) LIKE '%gale%') OR LOWER(`spy_locale`.`locale_name`) LIKE '%gale%') OR LOWER(Reorder) LIKE '%gale%')]

in /data/pim/staging/releases/20160413-152922/vendor/propel/propel/src/Propel/Runtime/ActiveQuery/Criteria.php (2505)

Url: %2Fcategory%2Findex%2FrootNodeTable%3Fdraw%3D5%26columns%255B0%255D%255Bdata%255D%3D0%26columns%255B0%255D%255Bname%255D%3D%26columns%255B0%255D%255Bsearchable%255D%3Dtrue%26columns%255B0%255D%255Borderable%255D%3Dfalse%26columns%255B0%255D%255Bsearch%255D%255Bvalue%255D%3D%26columns%255B0%255D%255Bsearch%255D%255Bregex%255D%3Dfalse%26columns%255B1%255D%255Bdata%255D%3D1%26columns%255B1%255D%255Bname%255D%3D%26columns%255B1%255D%255Bsearchable%255D%3Dtrue%26columns%255B1%255D%255Borderable%255D%3Dtrue%26columns%255B1%255D%255Bsearch%255D%255Bvalue%255D%3D%26columns%255B1%255D%255Bsearch%255D%255Bregex%255D%3Dfalse%26columns%255B2%255D%255Bdata%255D%3D2%26columns%255B2%255D%255Bname%255D%3D%26columns%255B2%255D%255Bsearchable%255D%3Dtrue%26columns%255B2%255D%255Borderable%255D%3Dtrue%26columns%255B2%255D%255Bsearch%255D%255Bvalue%255D%3D%26columns%255B2%255D%255Bsearch%255D%255Bregex%255D%3Dfalse%26columns%255B3%255D%255Bdata%255D%3D3%26columns%255B3%255D%255Bname%255D%3D%26columns%255B3%255D%255Bsearchable%255D%3Dtrue%26columns%255B3%255D%255Borderable%255D%3Dfalse%26columns%255B3%255D%255Bsearch%255D%255Bvalue%255D%3D%26columns%255B3%255D%255Bsearch%255D%255Bregex%255D%3Dfalse%26order%255B0%255D%255Bcolumn%255D%3D0%26order%255B0%255D%255Bdir%255D%3Dasc%26start%3D0%26length%3D10%26search%255Bvalue%255D%3DGale%26search%255Bregex%255D%3Dfalse%26_%3D1461139082462

Trace:
#0 /data/pim/staging/releases/20160413-152922/vendor/propel/propel/src/Propel/Runtime/ActiveQuery/ModelCriteria.php(1368): Propel\Runtime\ActiveQuery\Criteria->doCount(Object(Propel\Runtime\Connection\ConnectionWrapper))
#1 /data/pim/staging/releases/20160413-152922/vendor/propel/propel/src/Propel/Runtime/ActiveQuery/ModelCriteria.php(1348): Propel\Runtime\ActiveQuery\ModelCriteria->doCount(Object(Propel\Runtime\Connection\ConnectionWrapper))
#2 /data/pim/staging/releases/20160413-152922/vendor/spryker/spryker/Bundles/Gui/src/Spryker/Zed/Gui/Communication/Table/AbstractTable.php(448): Propel\Runtime\ActiveQuery\ModelCriteria->count()
#3 /data/pim/staging/releases/20160413-152922/vendor/spryker/spryker/Bundles/Category/src/Spryker/Zed/Category/Communication/Table/RootNodeTable.php(86): Spryker\Zed\Gui\Communication\Table\AbstractTable->runQuery(Object(Orm\Zed\Category\Persistence\SpyCategoryAttributeQuery), Object(Spryker\Zed\Gui\Communication\Table\TableConfiguration))
#4 /data/pim/staging/releases/20160413-152922/vendor/spryker/spryker/Bundles/Gui/src/Spryker/Zed/Gui/Communication/Table/AbstractTable.php(498): Spryker\Zed\Category\Communication\Table\RootNodeTable->prepareData(Object(Spryker\Zed\Gui\Communication\Table\TableConfiguration))
#5 /data/pim/staging/releases/20160413-152922/vendor/spryker/spryker/Bundles/Category/src/Spryker/Zed/Category/Communication/Controller/IndexController.php(48): Spryker\Zed\Gui\Communication\Table\AbstractTable->fetchData()
#6 [internal function]: Spryker\Zed\Category\Communication\Controller\IndexController->rootNodeTableAction()
```

For me it seems for a bug, because in RootNodeTable:prepareData it run's a query with $config where a column RootNodeTable::COL_REORDER is defined but not existing in Database.

**Comment by the-colorant** [comment]
@AndromedaXP Do you have a use case to search for root nodes? Would it be more helpful if for the solution the search will work on category node tree instead of note root nodes?

**Comment by the-colorant** [comment]
Root category table filter will be disabled, since we at all times show the whole category tree. Finding a necessary node is easy even without search field while the results are not paginated.

**Comment by the-colorant** [comment]
The issues is resolved. Please review this release https://github.com/spryker/Category/releases/tag/2.1.3

**Comment by AndromedaXP** [comment]
@the-colorant I thought you wanted to extend the search to all nodes?

**Comment by the-colorant** [comment]
Hi @AndromedaXP. We have considered the option of moving the search to the category tree instead of having it on root. However after internal discussion we concluded that the value search delivers on this page is not as significant as in pages like customers, orders, etc. For now we decided that it is not worth putting effort into this improvement. If later we see there is a demand and need to have a search on this page, we will reconsider. 
If you have any use case to show the importance of search for you on this page, I will be happy to hear about if for further consideration.

**Comment by mitja123** [comment]
Hi @the-colorant,
this topic came across after one of our Content Managers wanted to search for a specific page on CMS Pages in PIM. She has got the same Error. We need this functionality since our business depends on content and we generate a lot of content webpages.

**Comment by the-colorant** [comment]
@mitja123 This functionality is disabled only for category page. For CMS search we have a bug ticket and we will take care of it.
